[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
opSepolia = "${OP_SEPOLIA_RPC_URL}"
anvil = "http://localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${BASESCAN_API_KEY}" }
opSepolia = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
